- name: Stop Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Stop virtual machine
      azure_rm_virtualmachine:
        resource_group: demo-ansible-rg
        name: demovm1
        allocated: no