---
- hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: temp-ansible-rg
        location: eastus
      register: rg
    - debug:
        var: rg